# Use root/example as user/password credentials
version: '3.1'

services:

  neo4j-graph-db:
    image: neo4j:latest
    volumes:
     #- "workspace:/workspace/data-scientist-notes"
     - "/Users/kevin/bigdata/neo4j-data/:/data"
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: none # if comment on this line you can login by neo4j/neo4j

