# Use root/example as user/password credentials
version: '3.1'

services:

  # https://hub.docker.com/r/hdlee2u/gpdb-analytics/
  greenplum-analytics:
    image:  hdlee2u/gpdb-analytics
    command: /usr/sbin/sshd -D
    hostname: mdw
    volumes:
     #- "workspace:/workspace/data-scientist-notes"
     - "/Users/kevin/bigdata/greenplum-analytics-data/:/var/lib/gpdb"
     # - "/Users/kevin/bigdata/mysql-conf/:/etc/mysql/conf.d/"
    # restart: always
    ports:
      - 5435:5432
      - 28080:28080
    # environment:
      # MYSQL_ROOT_PASSWORD: trsadmin


