ln -s ~/dotfiles-mac/.emacs.d ~/.emacs.d
ln -s ~/dotfiles-mac/.mutt ~/.mutt
ln -s ~/dotfiles-mac/.oh-my-zsh ~/.oh-my-zsh
ln -s ~/dotfiles-mac/.spacemacs.d ~/.spacemacs.d
ln -s ~/dotfiles-mac/.tmux/.tmux.conf ~/.tmux.conf
ln -s ~/dotfiles-mac/.tmux ~/.tmux
ln -s ~/dotfiles-mac/.tmuxinator ~/.tmuxinator
ln -s ~/dotfiles-mac/.tmux/.tmux.conf.local ~/.tmux.conf.local
ln -s ~/dotfiles-mac/.tmux/.tmux.reset.conf ~/.tmux.reset.conf
ln -s ~/dotfiles-mac/.msmtprc ~/.msmtprc
ln -s ~/dotfiles-mac/.offlineimaprc ~/.offlineimaprc
ln -s ~/dotfiles-mac/.vimrc.local ~/.vimrc.local
ln -s ~/dotfiles-mac/.zshrc ~/.zshrc
ln -s ~/dotfiles-mac/.spacevim.d/ ~/.spacevim.d
ln -s ~/dotfiles-mac/.spacevim/ ~/.vim
ln -s ~/dotfiles-mac/.gemrc ~/.gemrc
ln -s ~/dotfiles-mac/.jupyter ~/.jupyter
ln -s ~/dotfiles-mac/.lein ~/.lein
ln -s ~/dotfiles-mac/.hammerspoon ~/.hammerspoon
ln -s ~/dotfiles-mac/.percol.d ~/.percol.d

