# Use root/example as user/password credentials
version: '3.1'

services:

  redis:
    image: redis
    command: redis-server --appendonly yes --requirepass trsadmin
    volumes:
     #- "workspace:/workspace/data-scientist-notes"
      - "/Users/kevin/bigdata/redis/data:/data"
      - "/Users/kevin/bigdata/redis/conf:/usr/local/etc/redis/"
    restart: always
    ports:
      - 6380:6379
    environment:
      MYSQL_ROOT_PASSWORD: trsadmin

