# Use root/example as user/password credentials
version: '3.1'

services:

  cassandra-node1:
    image: bitnami/cassandra:latest
    volumes:
     #- "workspace:/workspace/data-scientist-notes"
     - "/Users/kevin/bigdata/cassandra-node1-data/:/bitnami"
     # - "/Users/kevin/bigdata/cassandra-node1-conf/:/bitnami/cassandra/conf"
    ports:
      - 9042:9042
    links: 
      - cassandra-node2
    environment:
      CASSANDRA_CLUSTER_NAME: cassandra-cluster
      CASSANDRA_SEEDS: cassandra-node1,cassandra-node2
      CASSANDRA_TRANSPORT_PORT_NUMBER: 7000
      CASSANDRA_USER: cassandra
      # CASSANDRA_PASSWORD_SEEDER: yes
      CASSANDRA_PASSWORD: trsadmin
    # network: cassandra_network

  cassandra-node2:
    image: bitnami/cassandra:latest
    # links:
      # - cassandra-node1
    volumes:
     #- "workspace:/workspace/data-scientist-notes"
     - "/Users/kevin/bigdata/cassandra-node2-data/:/bitnami"
     # - "/Users/kevin/bigdata/cassandra-node2-conf/:/bitnami/cassandra/conf"
    environment:
      CASSANDRA_TRANSPORT_PORT_NUMBER: 7000
      CASSANDRA_CLUSTER_NAME: cassandra-cluster
      CASSANDRA_SEEDS: cassandra-node1,cassandra-node2
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: trsadmin
    # network: cassandra_network




