Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-18.04"
    config.vm.provision :shell, :path => "scripts/setup.sh"
    config.vm.network :forwarded_port, host: 8880, guest: 8080
    config.vm.network :forwarded_port, host: 9100, guest: 9000
    config.vm.network :forwarded_port, host: 9160, guest: 9060
#config.ssh.username = "root"
    config.ssh.password = "trsadmin"
    config.ssh.insert_key = true
    config.vm.synced_folder '.', '/vagrant', disabled:true
    config.vm.synced_folder '/Users/kevin/dotfiles-mac', '/home/vagrant/dotfiles-mac', owner:"vagrant", group:"vagrant", disabled: false
    config.vm.synced_folder '/Users/kevin/workspace', '/home/vagrant/workspace', owner:"vagrant", group:"vagrant", disabled: false

    config.vm.provider :virtualbox do |vb|
        vb.gui = false
        # Use VBoxManage to customize the VM. For example to change memory:
        vb.customize ["modifyvm", :id, "--name", "jhipster-devbox"]
        vb.customize ["modifyvm", :id, "--memory", "4096"]
        vb.customize ["modifyvm", :id, "--vram", 64]
        vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
        vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
        vb.customize ['modifyvm', :id, '--draganddrop', 'bidirectional']
    end
end
