# Use root/example as user/password credentials
version: '3.1'

services:
  kong-migrations:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    command: kong migrations bootstrap
    depends_on:
      - postgres-db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: postgres-db
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-trsadmin}
      KONG_PG_USER: ${KONG_PG_USER:-postgres}
    links:
      - postgres-db:postgres-db
  kong:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    hostname: kong
    depends_on:
      - postgres-db
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_CASSANDRA_CONTACT_POINTS: postgres-db
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: postgres-db
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-trsadmin}
      KONG_PG_USER: ${KONG_PG_USER:-postgres}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
    links:
      - postgres-db:postgres-db
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "8443:8443/tcp"
      - "8444:8444/tcp"
    restart: on-failure

  postgres-db:
    image: postgres:latest
    volumes:
     #- "workspace:/workspace/data-scientist-notes"
     - "/Users/kevin/bigdata/postgres-data/:/var/lib/postgresql/data"
     - "/Users/kevin/bigdata/mysql-conf/:/etc/mysql/conf.d/"
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
      POSTGRES_PASSWORD: ${KONG_PG_PASSWORD:-trsadmin}
      POSTGRES_USER: ${KONG_PG_USER:-postgres}
      PGDATA: /var/lib/postgresql/data
    # healthcheck:
      # test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-postgres}"]
      # interval: 30s
      # timeout: 30s
      # retries: 3
    restart: on-failure
    stdin_open: true
    tty: true
    ports:
      - 5433:5432
  kong-dashboard:
    image: pgbi/kong-dashboard
    command: start --kong-url http://kong:8001 --basic-auth root=trsadmin lujianmei=trsadmin
    depends_on:
      - kong
    # environment:
      # kong-url: http://kong:8001
      # basic-auth: root=trsadmin, lujianmei=trsadmin
    links:
      - kong:kong
    ports:
      - 8480:8080
    restart: on-failure
